require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'mdbAPP' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'


  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'mdbAPPTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'mdbAPP-tvOS' do
  # Pods for mdbAPP-tvOS

  target 'mdbAPP-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
